version: '3'

services:
  mysql_task_manager:
    image: mysql:latest
    container_name: mysql_task_manager_container
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: task_manager_database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: